name: Valid JSON

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Validate JSON
      run: env DEVELOPER_DIR="/Applications/Xcode_12.0.app" swift validate.swift
      env:
        GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
