name: Nightly Audit

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  run_nightly:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run nightly script
      run: env DEVELOPER_DIR="/Applications/Xcode_12.0.app" xcrun swift nightly.swift
      env:
        GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
    - name: Run validation script
      run: env DEVELOPER_DIR="/Applications/Xcode_12.0.app" xcrun swift validate.swift
      env:
        GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GH_API_TOKEN }}
        commit-message: Updated Packages
        title: '[Nightly] Updated Packages'
        body: |
          :robot: This is an automated change
          
          - Removed any redirects
          - Removed any duplicates
          - Removed any deleted repositories
          - Added any unknown dependencies
    - name: Check outputs
      run: echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
